### ISSUE TITLE
Automation Menu is Not loading.

### ISSUE THREAD

**Issue by AnnoyingPriannacompy** [Farigh/pokeclicker-automation#216] opened 2023-01-13 04:17 UTC
pokeclicker is Saying it's already been Intilazied, But it has not been

**Comment by Farigh** [comment] 2023-01-13 07:25
Hi, I'm afraid I'll need a bit more details about this issue.

How so you use this suite ?

**Comment by Essoheli** [comment] 2023-01-13 22:26
I'm having the same problem. While monitoring the console during a reload, I got the following error during Automation Start -

Uncaught TypeError: sweetData[spinType] is undefined
    __internal__addInfo https://www.pokeclicker.com/ line 90 > injectedScript:146
    __internal__buildMenu https://www.pokeclicker.com/ line 90 > injectedScript:72
    initialize https://www.pokeclicker.com/ line 90 > injectedScript:15
    timer https://www.pokeclicker.com/ line 90 > injectedScript:62
    setInterval handler*start https://www.pokeclicker.com/ line 90 > injectedScript:44
    watcher https://www.pokeclicker.com/ line 30 > injectedScript:157
    setInterval handler*__setupAutomationRunner https://www.pokeclicker.com/ line 30 > injectedScript:128
    loadFromUrl https://www.pokeclicker.com/ line 30 > injectedScript:57
    onreadystatechange moz-extension://036bb9e0-b35b-42db-816e-41067f354bc7/userscripts/Pokeclicker Automation.user.js?id=c40e06d7-ef14-4e34-b53a-16d87f40d182:32
    EventHandlerNonNull*window["__f__lcv5ikj6.6g"]/< moz-extension://036bb9e0-b35b-42db-816e-41067f354bc7/userscripts/Pokeclicker Automation.user.js?id=c40e06d7-ef14-4e34-b53a-16d87f40d182:22
    St https://www.pokeclicker.com/:9
    window["__f__lcv5ikj6.6g"]/< moz-extension://036bb9e0-b35b-42db-816e-41067f354bc7/userscripts/Pokeclicker Automation.user.js?id=c40e06d7-ef14-4e34-b53a-16d87f40d182:1
    "__f__lcv5ikj6.6g" moz-extension://036bb9e0-b35b-42db-816e-41067f354bc7/userscripts/Pokeclicker Automation.user.js?id=c40e06d7-ef14-4e34-b53a-16d87f40d182:1
    St https://www.pokeclicker.com/:9
    n https://www.pokeclicker.com/:71
    <anonymous> https://www.pokeclicker.com/:74
    g https://www.pokeclicker.com/:68
line 90 > injectedScript:146:13

**Comment by Dessastuff** [comment] 2023-01-13 22:34
Can verify it's not just one loadout, it's across the board. even to your own app.asar desktop

**Comment by BigJonSD** [comment] 2023-01-13 22:49
Not sure if this is related but the 0.10.7 update was just released and seems completely incompatible with the current script.

**Comment by igorlan** [comment] 2023-01-13 23:44
> Not sure if this is related but the 0.10.7 update was just released and seems completely incompatible with the current script.

same.

**Comment by Farigh** [comment] 2023-01-14 01:39
This might indeed be an update regression, I'll take a look at it quickly

**Comment by Altizar** [comment] 2023-01-14 05:35
the broken line is 
`this.__internal__addInfo(sweetData, GameConstants.AlcremieSpins.at7Above10, currentSweetContainer);`
it looks like the constant was changed from at7Above10 to at5Above10 in the latest release

**Comment by cfedey** [comment] 2023-01-14 05:45
That does seem to fix it. I also changed the other `at7above10` on line 111 to `at5above10` but that didn't seem to change anything for better or worse.

**Comment by djvw24** [comment] 2023-01-14 10:12
> the broken line is `this.__internal__addInfo(sweetData, GameConstants.AlcremieSpins.at7Above10, currentSweetContainer);` it looks like the constant was changed from at7Above10 to at5Above10 in the latest release

On my script in TamperMonkey, the line I'm seeing the issue with is :
            AutomationComponentLoader.loadFromUrl(pokeclickerAutomationReleaseUrl);

Error: eslint no-undef - 'AutomationComponentLoader' is not defined

**Comment by Farigh** [comment] 2023-01-14 14:22
> > the broken line is `this.__internal__addInfo(sweetData, GameConstants.AlcremieSpins.at7Above10, currentSweetContainer);` it looks like the constant was changed from at7Above10 to at5Above10 in the latest release
> 
> On my script in TamperMonkey, the line I'm seeing the issue with is : AutomationComponentLoader.loadFromUrl(pokeclickerAutomationReleaseUrl);
> 
> Error: eslint no-undef - 'AutomationComponentLoader' is not defined

This "error" in tempermonky is not an error, it's normal. Since the tempoermonkey script downloads the suite, it does not know that this symbol will be available yet.

**Comment by Farigh** [comment] 2023-01-14 14:28
@AnnoyingPriannacompy is this issue fixed for you ?

**Comment by heyboots** [comment] 2023-01-14 14:44
I can confirm it is working as of just now. I had the same issue last night after the game updated.

**Comment by AnnoyingPriannacompy** [comment] 2023-01-14 15:08
> @AnnoyingPriannacompy is this issue fixed for you ?

Haven't checked yet bout too

**Comment by AnnoyingPriannacompy** [comment] 2023-01-14 15:15
It has not changed.

**Comment by Farigh** [comment] 2023-01-14 16:49
I'll need more detail about you configuration as I cannot reproduce the problem

**Comment by AnnoyingPriannacompy** [comment] 2023-01-16 15:57
It's alright now, I don't what caused it, but it seems to be that Pokeclicker itself had the issue.

**Comment by Farigh** [comment] 2023-01-16 16:43
Thanks for the feedback, I'm closing the issue then :)

**Closed by Farigh** 2023-01-16 16:43 UTC
Labels: bug
