### ISSUE TITLE
Allow Quest Automation to recognize hatched Pokemon as caught

### ISSUE THREAD

**Issue by elementgermanium** [Farigh/pokeclicker-automation#135] opened 2022-09-16 20:24 UTC
### Is your feature request related to a problem? Please describe.
The Focus On: Quests automation doesn't seem to utilize the hatchery for 'catch X Pokemon' quests, despite hatched eggs counting toward said quests, sometimes leading to less optimal decisions- for example, for quests to catch Fairy Pokemon and obtain Fighting gems, it would be more efficient to hatch Fairy-types while automatically clearing a Fighting gym, however the automation instead goes to Kanto route 3, likely due to the presence of Jigglypuff and Mankey, for much slower overall progress.

### Describe the solution you'd like
Allow the quest automation to recognize hatched Pokemon as caught Pokemon for quests and prioritize hatchery use when normal catching is inefficient.

**Comment by Farigh** [comment] 2022-09-17 10:38
Duplicate of #89

**Closed by Farigh** 2022-09-17 10:38 UTC
