### ISSUE TITLE
Auto Safari Zone and Hatcher Achievements

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [Farigh/pokeclicker-automation#308] opened 2023-08-02 20:15 UTC
### Is your feature request related to a problem? Please describe.
No.
### Describe the solution you'd like
I am nearly done with all the achievements. Still need the Alola, Galar, and Magikarp Jump achievements. But the Safari Zone is a bit of a challenge without auto.
### Describe alternatives you've considered
No
### Additional context
No

**Comment by Farigh** [comment] 2023-08-02 21:08
Duplicate of  #49

**Closed by Farigh** 2023-08-02 21:08 UTC
Labels: duplicate
