### ISSUE TITLE
Focus.Quest: Farming for capture <N> <type> Pokemon

### ISSUE THREAD

**Issue by dox4242** [Farigh/pokeclicker-automation#198] opened 2022-11-13 10:31 UTC
Besides the classic method of throwing Pokeballs on routes, the hatchery can be used, often faster, to complete these quests. I'm unsure how to request it to be implemented, whether with a toggle switch, or just replacing the code under the hood, but I don't think you need my suggestion in that regard. Thanks for the awesome tool suite!

**Comment by Farigh** [comment] 2022-11-15 22:42
Closing as duplicate of #89

**Closed by Farigh** 2022-11-15 22:42 UTC
