### ISSUE TITLE
Hatchery: Uses current filter/sort and one option to consider EV.

### ISSUE THREAD

**Issue by linkdest** [Farigh/pokeclicker-automation#101] opened 2022-08-03 15:52 UTC
### Is your feature request related to a problem? Please describe.
The current hatchery only breed by highest efficiency. It would be great to allow users to hatch by their prefference. For exemple: I only want to breed  legendaries, or sort by times hatched.  The other suggetion is use a toggle to allow users to choose if they want to the breeding efficiency formula considers the current EV or not.

### Describe the solution you'd like
To solve the first suggestion, I suggest putting the pokemons conform they are displayed in the hatchery list.

**Comment by Farigh** [comment] 2022-08-03 17:09
Duplicate of #48

**Closed by Farigh** 2022-08-03 17:09 UTC
