### ISSUE TITLE
Focus.PokérusCure - CaughtBall reset

### ISSUE THREAD

**Issue by jensver** [Farigh/pokeclicker-automation#290] opened 2023-05-04 11:06 UTC
In /src/lib/Focus/PokerusCure.js on line 211 there is: App.game.pokeballs.alreadyCaughtSelection = GameConstants.Pokeball.None;
I don't understand why this is not using the default value for caught in the Focus settings?

**Comment by Farigh** [comment] 2023-05-04 12:17
This is done because we are focusing on Poker us cure, so we only want to catch contagious pokémons, not every single one of them.

**Comment by jensver** [comment] 2023-05-05 08:18
The reason why I want to catch already caught pokemon is because in Galar and Alola the amount of dungeon tokens needed to clear a dungeon is very high. But when you catch all poke in the dungeon, you get dungeon tokens for each catch, so you need less dungeon tokens for a dungeon clear.

**Comment by Farigh** [comment] 2023-05-05 08:52
The automation automatically switches to dungeon token farming when you run out of tokens. So it should not be a concern.

I'll eventually add an option to force catching every pokemons

**Comment by Farigh** [comment] 2023-05-07 13:24
@jensver This should has been addressed by #294

Can you confirm that it matches your expected behaviour ?

**Closed** 2023-05-24 10:48 UTC
Labels: enhancement, Not a bug
