### ISSUE TITLE
New Version 0.10.20

### ISSUE THREAD

**Issue by MatPietrzyk** [Farigh/pokeclicker-automation#363] opened 2024-06-18 14:29 UTC
Pretty much everything broke with new update.

**Comment by Farigh** [comment] 2024-06-18 17:00
I saw the notification on Discord earlier today and I assumed this would happen....

Unfortunately I don't have time to look into it until late this weekend, fill free to push a PR in the meantime if you want/can.

**Comment by roscoejp** [comment] 2024-06-18 21:45
FYI you can "fix" the farming and underground automation components by disabling the new UI elements (since it puts them back into the shortcut list):
uncheck `Settings > Display > Farm > 'Show farm module on main screen'`
uncheck `Settings > Display > Underground> 'Show underground module on main screen'`

**Comment by Farigh** [comment] 2024-06-18 22:05
I fixed the most obvious regressions.

Can you provide a save or a way to reproduce the underground bug @roscoejp. 
I don't have the problem on my save

**Comment by roscoejp** [comment] 2024-06-23 01:23
Not able to reproduce the farming/mining issues while they're on the main screen anymore. Not sure why fixes to the routes/dungeons/gyms logic would've effected this but seems to work now.

(Previously wasn't able to get the farm/mine to work while they were on the main screen, but they'd still work when removed from main screen)

**Comment by Farigh** [comment] 2024-06-24 13:42
I've played a bit with the new update this weekend and did not encounter any problem.

I'll keep this issue open for a week or so to trace any new update issue. After that I'll close it.

**Comment by Kaysera14** [comment] 2024-06-27 14:27
The auto-safari feature seems to be broken, I've recently started a new run with all challenges and it doesn't start. Dunno if I'm forgetting something that needs to be unlocked prior or maybe it's broken.

**Comment by Farigh** [comment] 2024-06-30 10:46
I'm closing this, since it does not seem to be needed anymore

**Closed by Farigh** 2024-06-30 10:46 UTC
Labels: bug
