### ISSUE TITLE
v0.10.14 update (august 20, 2023) breaks entire script on all challenge.

### ISSUE THREAD

**Issue by simcowking** [Farigh/pokeclicker-automation#309] opened 2023-08-21 00:47 UTC
### Describe the bug
Loading all challenge file, the auto battle gyms/trivia section look blanked. Turning on and off a few get them to 'work' temporarily. Hatchery always does by national dex, farming doesn't appear to unlock new berries (even with multiple locked still), autoshop doesn't appear to purchase anything unless toggled on and off. 

Setting to EXP auto doesn't move route.
Setting to Money doesn't move.
Setting to DT does work.
Setting to quests does accept new quest, but won't do anything about them. 
Achievements nothing.
Pokerus cure does send me back to route 1.

Selecting a XXX Gem sends me to a town, never does a gym fight.

Mining does appear to work fully. (well I only have it set to use potions and auto mine... since autoshop stopped working... I guess this will break soon)

Roamers button does nothing.
As evident, can't go to a specific town as everything is blank.

![image](https://github.com/Farigh/pokeclicker-automation/assets/138606129/042e57a1-de0b-4642-b1c1-06b99baf4a49)

----

Everything was working as of August 20th in the morning before the update.

EDITING TO ADD:

Works just fine on my 2 challenge file.

**Comment by cfedey** [comment] 2023-08-21 12:35
Chiming in with my own version of things. Since today's version (0.10.15), focuses are broken for me on 2-challenge and all-challenge saves. 

On 2-challenge:

- Experience is broken.
- Money is broken.
- Dungeon Tokens is fine.
- Quests seems to be fine, but I didn't test all quest types.
- Achievements is broken, and it was working on 0.10.14 yesterday.
- Pokérus cure I can't test because I have everything that it can automate.

On all-challenge:

- Experience is fine.
- Money is fine.
- Dungeon Tokens is fine.
- Quests again seems to be fine. Didn't test all types.
- Achievements is broken and says "No more achievements to automate" when that's very much not true. I wonder if it's trying to go to New Island even though the event isn't up.
- Pokérus cure is fine.

I am not experiencing the above issue of the roamer or town buttons not working. They work fine on both of my saves.

**Comment by Farigh** [comment] 2023-08-21 16:04
@cfedey could you provide your saves reproducing the issue, I could not reproduce any on my own save.
Your browser details would be appreciated as well.
I only have a default-challenges save and everything seems to work fine on my browser (`Firefox 116.0.3 (64 bits)`)

**Comment by Farigh** [comment] 2023-08-21 16:20
I found a regression and fixed it, tell me if it fixed your issues

**Comment by cfedey** [comment] 2023-08-21 17:59
Everything seems to work fine now on the 2-challenge save. On the all-challenge save, everything works except Achievements.
[[v0.10.15] PokeClickerSave_CM.txt](https://github.com/Farigh/pokeclicker-automation/files/12399458/v0.10.15.PokeClickerSave_CM.txt)

**Comment by simcowking** [comment] 2023-08-21 18:13
OP here:

2 Challenge: Quests nearly works (Battle frontier is accepted but not traveled to. Disabled for time being and it works fine)

Everything else working as intended to the best of my testing (pokerus unable to test on 2C)

For All Challenges:

Not as thoroughly checked (just takes so much longer to hatch eggs)
Hatchery working (tested with focus on mega evolves, first 15 hatchery placements were megas)
Mining still works
Farming works.
Autoshop working.

Trivia buttons are working again (roamers, go to specific city)


Thanks for quick turn around.


For clarity as cfedey just responded while typing this:

My 2C is at Orre for achievements (everything done prior to update)
My AC is only at Johto route 34 for achievements. So the new stuff isn't on the radar for it to test with)

**Comment by Farigh** [comment] 2023-08-22 16:33
> Everything seems to work fine now on the 2-challenge save. On the all-challenge save, everything works except Achievements. [[v0.10.15] PokeClickerSave_CM.txt](https://github.com/Farigh/pokeclicker-automation/files/12399458/v0.10.15.PokeClickerSave_CM.txt)

Thanks for your save, I did not have Orre unlocked on my own save.
For what I can see from your save, it seems legit that the automation does not work for achievements, since :
- The automation only handles the following achievement types :
  - Route defeats
  - Clear Gym
  - Clear Dungeon
- It requires the location to be accessible

In your save, you have `Orre` and `New Island` achievements that match are listed, however:
  - Orre is unlocked but none of the location are accessible except `Outskirt Stand`
  - New Island is only available during the Armored Mewtwo event
  
Tell me if I missed something ?

**Comment by cfedey** [comment] 2023-08-22 17:13
Yeah you're right. I hadn't worked on that save yet since I was doing achievements on my 2-challenge save first, so I didn't think about it. I started working on my all-challenge save today, and the Achievement focus seems to be working fine. 

So, no problems to report anymore. Thanks for your help. Sorry for the hassle.

**Comment by Farigh** [comment] 2023-08-22 18:41
I added 2 new issues for the support of new quest types.
  - [x] ~#312~
  - [x] #313
  
I pushed an implementation for the 1st one, I'll work one the 2nd one later this week (hopefully).

I'm closing this issue, don't hesitate to open a new one if you find new problems

**Closed by Farigh** 2023-08-22 18:41 UTC
Labels: bug
